spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      leak-detection-threshold: 5000
      connection-timeout: 5000
      validation-timeout: 5000
      idle-timeout: 60000
      max-life-time: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8888
